-- AlterTable
ALTER TABLE `PurchaseOrder` ADD COLUMN `currency` VARCHAR(191) NULL DEFAULT 'INR',
    ADD COLUMN `exchangeRate` DECIMAL(12, 4) NULL DEFAULT 1.0000,
    ADD COLUMN `foreignGrandTotal` DECIMAL(12, 2) NULL,
    ADD COLUMN `foreignSubTotal` DECIMAL(12, 2) NULL,
    ADD COLUMN `gstRate` DECIMAL(5, 2) NULL,
    MODIFY `gstType` ENUM('IGST_5', 'IGST_12', 'IGST_18', 'IGST_28', 'IGST_EXEMPTED', 'LGST_5', 'LGST_12', 'LGST_18', 'LGST_28', 'LGST_EXEMPTED', 'IGST_ITEMWISE', 'LGST_ITEMWISE') NOT NULL;
